### ISSUE TITLE
Submit Stat Ideas!

### ISSUE THREAD

**Issue by MF64-AnEngieMain** [MF64-AnEngieMain/TF2-Weapon-Generator-2.0#1]
Please structure your comments like this:
Type: Percentage, Additive, or Absolute
Name (what it'll appear as while selecting)
Description (what it'll say when added)

OR

Make a commit!

**Comment by ice-nuclearcrackhead239** [comment]
A few ubercharges

Type: Absolute
**Übercharge**
Makes the target invincible for 8 seconds when ubered.

Type: Absolute
**Megaheal**
300% Healing when ubered, knockback invulnerability.

Type: Absolute
**Crit Boost**
100% Crit chance when ubered.

**Comment by MF64-AnEngieMain** [comment]
> A few ubercharges
> 
> Type: Absolute
> **Übercharge**
> Makes the target invincible for 8 seconds when ubered.
> 
> Type: Absolute
> **Megaheal**
> 300% Healing when ubered, knockback invulnerability.
> 
> Type: Absolute
> **Crit Boost**
> 100% Crit chance when ubered.

Thanks for the suggestion!
